### ISSUE TITLE
can game.lua can add wav sound ? or locate the wav sound ?

### ISSUE THREAD

**Issue by OldGamers** [icculus/DirkSimple#16]
I have the blips and bloops sound from Dragons lair. Im not expert on github or lua coding but is it posible to include a sound folder in the lair folder where game lua is located ? here the wav sound for the game 
[lair.zip](https://github.com/icculus/DirkSimple/files/11038051/lair.zip)

**Comment by icculus** [comment]
I'm hooking up audio code right now, over in #15, and then we can include bleeps and bloops!
