### ISSUE TITLE
video codec options

### ISSUE THREAD

**Issue by ckeisc** [icculus/DirkSimple#28]
Would it be possible for DirkSimple to support m2v + ogg or a wider range of video formats? I followed the instruction to re-encode the m2v + ogg file to Theora and my windows 10 running on 2012 Macbook Pro (4th gen i5 and its iGPU) can't seem to playback the video smoothly. Not just in Retroarch / DirkSimple, the same Theora video is also choppy when play back using a media player (MPC-HC). I am not totally sure where the bottleneck was as CPU and GPU are both under 20% utilization, but the playback just looked like a slide show, I eyeball 5 fps maybe. The original m2v could be played back perfectly.

Would it be possible for DirkSimple to work with the m2v and ogg pair? or perhaps other container + codec that have widespread HW decoding support across wide range of HW?

**Comment by icculus** [comment]
The goal was to _not_ add multiple codecs here, but in case it's an encoding issue with your data, hit me up at icculus@icculus.org and I'll help you out.
